name: Build bitcoinj with Containerfile

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build with Containerfile
        run: |
          docker build --file build.Containerfile --output out .
          
      - name: List output
        run: find out -name "*.jar"
        
      - name: Upload JARs
        uses: actions/upload-artifact@v4
        with:
          name: bitcoinj-0.17.1-build
          path: |
            out/core/*.jar
            out/wallettool/
